export const surpriseMePrompts = [
  "Create a cyberpunk anime character with neon powers",
  "Illustrate a magical spell being cast in space",
  "Animate a futuristic city with flying cars and cyberpunk elements",
  "Render a digital art representation of a cyberpunk invasion on a distant planet",
  "Visualize a magical creature with neon wings in a neon-lit forest",
  "Draw a cyberpunk hero battling robots in a digital art world",
  "Design a futuristic city with floating buildings and stars in a neon night sky",
  "Create a cyberpunk villain with a magic-infused weapon",
  "Illustrate a spell being cast in a futuristic city with floating platforms",
  "Animate a cyberpunk hero with a magic-infused vehicle on a journey through the stars",
  "Render a magical kingdom with neon rivers and mountains in a digital art world",
  "Visualize a cyberpunk hero in a neon-lit city, facing off against a dangerous enemy",
  "Draw a futuristic city with flying cars and neon-lit buildings in a starry night sky",
  "Design a cyberpunk hero with a magic-infused gadget, ready for any challenge",
  "Create a futuristic city with floating markets and stars in a digital art world",
  "Illustrate a spell being cast in a cartoon world with shooting stars",
  "Animate a cyberpunk hero in a digital art world with aliens and robots",
  "Render a magical kingdom with neon rivers and floating islands in a digital art world",
  "Visualize a cyberpunk hero in a neon-lit city, saving the day from an impending disaster",
  "Draw a futuristic city with flying cars and neon signs in a star-filled night sky",
  "Design a cyberpunk hero with a magic-infused armor, ready for any mission",
  "Create a futuristic city with floating gardens and stars in a digital art world",
  "Illustrate a spell being cast in a neon-lit forest, surrounded by magical creatures",
  "Animate a cyberpunk hero in a digital art world with robots and flying vehicles",
  "Render a magical creature with neon powers in a neon-lit world",
  "Visualize a cyberpunk hero in a neon-lit city, fighting against a dangerous organization",
  "Draw a futuristic city with flying cars and neon-lit buildings in a digital art world",
  "Design a cyberpunk hero with a magic-infused device, on a quest to save the future",
  "Create a futuristic city with floating parks and stars in a digital art world",
  "Illustrate a spell being cast in a cyberpunk city, surrounded by technology",
  "Animate a cyberpunk hero in a digital art world with aliens and magic",
  "Render a magical creature with neon tentacles in a neon-lit world",
  "Visualize a cyberpunk hero in a neon-lit city, unraveling a mysterious conspiracy",
  "Draw a futuristic city with flying cars and neon-lit skyscrapers in a digital art world",
  "Design a cyberpunk hero with a magic-infused weapon, taking on impossible odds",
  "Create a futuristic city with floating bridges and stars in a digital art world",
  "Illustrate a spell being cast in a futuristic city with flying vehicles and neon lights",
  "Animate a cyberpunk hero in a digital art world with robots and magic spells",
  "Render a magical creature with neon claws in a neon-lit world",
  "Visualize a cyberpunk hero in a neon-lit city, discovering secrets and uncovering truth",
  "Draw a futuristic city with flying cars and neon-lit streets in a digital art world",
  "Design a 4K realistic cyberpunk anime character with intricate armor and weapons",
  "Illustrate a magical spell casting scene in a hyper-realistic 8K world",
  "Animate a 3D cartoon spaceship flying through space with wacky aliens and unexpected twists",
  "Render a realistic digital art landscape of a war-torn world showcasing the destruction and beauty of war",
  "Visualize a dystopian cyberpunk society in a 4K HD world under the stars, with neon lights illuminating the dark streets",
  "Create a 3D hyper-realistic red queen in a neon-lit forest",
  "Draw a 8K realistic cyberpunk hero battling robots in a digital art world",
  "Design a 4K HD futuristic city with floating buildings and stars in a neon night sky",
  "Illustrate a spell being cast in a futuristic city with floating platforms in an 8K unreal world",
  "Animate a cyberpunk hero with a magic-infused vehicle on a journey through the stars in a 3D world",
  "Render a magical kingdom with neon rivers and mountains in a hyper-realistic digital art world",
  "Visualize a cyberpunk hero in a neon-lit city, facing off against a dangerous enemy in a 4K HD world",
  "Draw a futuristic city with flying cars and neon-lit buildings in a starry night sky in an 8K world",
  "Design a cyberpunk hero with a magic-infused gadget, ready for any challenge in a 4K world",
  "Illustrate a spell being cast in a cartoon world with shooting stars in a 3D world",
  "Animate a cyberpunk hero in a digital art world with aliens and robots in a 4K HD world",
  "Render a magical kingdom with neon rivers and floating islands in a realistic digital art world",
  "Visualize a cyberpunk hero in a neon-lit city, saving the day from an impending disaster in an 8K world",
  "Draw a futuristic city with flying cars and neon signs in a star-filled night sky in a 4K world",
  "Design a cyberpunk hero with a magic-infused armor, ready for any mission in an 8K world",
  "Illustrate a spell being cast in a neon-lit forest, surrounded by magical creatures in a 4K world",
  "Animate a cyberpunk hero in a digital art world with robots and flying vehicles in a 8K HD world",
  "Render a magical creature with neon powers in a hyper-realistic neon-lit world",
  "Visualize a cyberpunk hero in a neon-lit city, fighting against a dangerous organization in a 4K world",
  "Draw a futuristic city with flying cars and neon-lit buildings in a digital art world in an 8K HD world",
  "Design a cyberpunk hero with a magic-infused device, on a quest to save the future in a 4K world",
  "Illustrate a spell being cast in a cyberpunk city, surrounded by technology in an 8K world",
  "Animate a cyberpunk hero in a digital art world with aliens and magic in a 4K HD world",
  "Render a magical creature with neon tentacles in a realistic neon-lit world",
  "Visualize a cyberpunk hero in a neon-lit city, unraveling a mysterious conspiracy in an 8K world",
];
