export const surpriseMePrompts = [
  "Design a futuristic 4K cityscape with neon lights",
  "Create an 8K cyberpunk character",
  "Illustrate a magical spell casting in the future",
  "Animate a cartoon spaceship flying through space",
  "Render a digital art landscape in a war-torn world",
  "Visualize a cyberpunk society under the stars",
  "Draw a magical creature in a neon-lit forest",
  "Design a future city with flying cars and stars",
  "Create a cyberpunk anime character",
  "Animate a magical spell being cast during a war",
  "Render a digital art representation of a starry night",
  "Visualize a futuristic city with cyberpunk elements",
  "Illustrate a cartoon character casting a spell in space",
  "Animate a war fought between cyberpunk and magical beings",
  "Draw a futuristic city with neon lights and flying cars",
  "Create a cyberpunk hero fighting for justice in space",
  "Visualize a magical spell being cast in a neon city",
  "Render a digital art representation of a cyberpunk invasion",
  "Animate a cartoon character exploring the stars",
  "Illustrate a futuristic city with a cyberpunk vibe",
  "Design a magical world with floating islands and stars",
  "Create a cyberpunk villain with a neon robotic arm",
  "Animate a spell being cast in a digital art world",
  "Draw a futuristic city with flying cars and neon lights",
  "Render a cyberpunk hero battling robots in space",
  "Visualize a magical forest with neon-lit trees",
  "Animate a cartoon character flying through the stars",
  "Illustrate a digital art representation of a futuristic war",
  "Design a cyberpunk character with a magic-infused weapon",
  "Create a futuristic city with floating platforms and stars",
  "Render a spell being cast in a neon-lit city",
  "Animate a cyberpunk hero in a digital art world",
  "Draw a magical creature with neon powers",
  "Visualize a futuristic city with flying cars and cyberpunk elements",
  "Illustrate a spell being cast in a cartoon world",
  "Animate a cyberpunk villain in a neon-lit city",
  "Render a digital art representation of a magical kingdom",
  "Design a futuristic city with floating buildings and stars",
  "Create a cyberpunk hero with a magic-infused vehicle",
  "Visualize a spell being cast in a futuristic city",
  "Animate a cyberpunk hero battling robots in a digital art world",
  "Illustrate a magical creature in a neon-lit forest",
  "Draw a futuristic city with flying cars and neon-lit buildings",
  "Render a cyberpunk hero in a digital art universe",
  "Animate a spell being cast in a cartoon world with stars",
  "Visualize a magical kingdom with neon-lit trees",
  "Design a cyberpunk hero with a magic-infused armor",
  "Create a futuristic city with floating gardens and stars",
  "Render a spell being cast in a neon-lit forest",
  "Animate a cyberpunk hero in a digital art world with robots",
  "Illustrate a magical creature with neon wings",
  "Draw a futuristic city with flying cars and neon signs",
  "Visualize a spell being cast in a cyberpunk city",
  "Animate a cyberpunk hero in a digital art world with aliens",
  "Render a magical kingdom with neon rivers and mountains",
  "Design a cyberpunk hero with a magic-infused gadget",
  "Create a futuristic city with floating markets and stars",
  "Visualize a spell being cast in a cartoon world with stars",
];
